"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8z!+$)0n53udii+@a)2q@@az)=n^3o!u%a6t5fy2-y$4u_*8p@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
	
    'streets',
	'django_extensions',
	'djrichtextfield',
	
    'tinymce'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ru-RU'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# STATIC_ROOT = '' # это уже когда к серверу придем
# CKEDITOR_BASEPATH = STATIC_URL + "ckeditor/ckeditor/"

# CKEDITOR_5_IMAGE_BACKEND = 'Pillow'
# CKEDITOR_5_UPLOAD_PATH = '/photos/'

# CKEDITOR_5_CONFIGS = {
#     'default': {
# 		'language': 'ru',
# 		'heading': {
#             'options': [
#                 {'model': 'paragraph', 'title': 'Параграф', 'class': 'ck-heading_paragraph'},
#                 {'model': 'heading1', 'view': 'h1', 'title': 'Заголовок 1', 'class': 'ck-heading_heading1'},
#                 {'model': 'heading2', 'view': 'h2', 'title': 'Заголовок 2', 'class': 'ck-heading_heading2'},
#                 {'model': 'heading3', 'view': 'h3', 'title': 'Заголовок 3', 'class': 'ck-heading_heading3'},
#                 {'model': 'heading4', 'view': 'h4', 'title': 'Заголовок 4', 'class': 'ck-heading_heading4'},
#                 {'model': 'heading5', 'view': 'h5', 'title': 'Заголовок 5', 'class': 'ck-heading_heading5'},
#                 {'model': 'heading6', 'view': 'h6', 'title': 'Заголовок 6', 'class': 'ck-heading_heading6'},
#             ]
#         },
#         'toolbar': [
# 			'heading', '|',
# 			'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor', '|', 
# 			'bold', 'italic', 'underline','|',
# 			'link', 'insertImage', 'ckbox', 'mediaEmbed', 'insertTable', 'insertTableLayout', 'blockQuote', '|',
# 			'outdent', 'indent'
#         ],
# 		'balloonToolbar': ['bold', 'italic', '|', 'link', 'insertImage'],
# 		'heading': {
#             'options': [
#                 {
#                     'model': 'paragraph',
#                     'title': 'Paragraph',
#                     'class': 'ck-heading_paragraph'
#                 },
#                 {
#                     'model': 'heading1',
#                     'view': 'h1',
#                     'title': 'Heading 1',
#                     'class': 'ck-heading_heading1'
#                 },
#                 {
#                     'model': 'heading2',
#                     'view': 'h2',
#                     'title': 'Heading 2',
#                     'class': 'ck-heading_heading2'
#                 },
#                 {
#                     'model': 'heading3',
#                     'view': 'h3',
#                     'title': 'Heading 3',
#                     'class': 'ck-heading_heading3'
#                 },
#                 {
#                     'model': 'heading4',
#                     'view': 'h4',
#                     'title': 'Heading 4',
#                     'class': 'ck-heading_heading4'
#                 },
#                 {
#                     'model': 'heading5',
#                     'view': 'h5',
#                     'title': 'Heading 5',
#                     'class': 'ck-heading_heading5'
#                 },
#                 {
#                     'model': 'heading6',
#                     'view': 'h6',
#                     'title': 'Heading 6',
#                     'class': 'ck-heading_heading6'
#                 }
#             ]
#         },
# 		'image': {
#             'toolbar': [
#                 'toggleImageCaption', 'imageTextAlternative', '|',
#                 'imageStyle:inline', 'imageStyle:wrapText', 'imageStyle:breakText', '|',
#                 'resizeImage', '|',
#                 'ckboxImageEdit'
#             ]
# 	    },
#         'table': {
#             'contentToolbar': ['tableColumn', 'tableRow', 'mergeTableCells', 'tableProperties', 'tableCellProperties']
#         },
# 		'link': {
#             'addTargetToExternalLinks': 'true',
#             'defaultProtocol': 'https://',
#             'decorators': {
#                 'toggleDownloadable': {
#                     'mode': 'manual',
#                     'label': 'Downloadable',
#                     'attributes': {
#                         'download': 'file'
#                     }
#                 }
#             }
# 	    },
#         'placeholder': 'Пишите здесь пост...'
# 	},
# }

CKEDITOR_IMAGE_BACKEND = 'Pillow'
CKEDITOR_UPLOAD_PATH = '/photos/'

CKEDITOR_CONFIGS = {
    'default': {
		'language': 'ru',
        # 'toolbar': [
		# 	'heading', '|',
		# 	'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor', '|', 
		# 	'bold', 'italic', 'underline','|',
		# 	'link', 'insertImage', 'ckbox', 'mediaEmbed', 'insertTable', 'insertTableLayout', 'blockQuote', '|',
		# 	'outdent', 'indent'
        # ],
		'toolbar': 'full',
		'heading': {
            'options': [
                {'model': 'paragraph', 'title': 'Параграф', 'class': 'ck-heading_paragraph'},
                {'model': 'heading1', 'view': 'h1', 'title': 'Заголовок 1', 'class': 'ck-heading_heading1'},
                {'model': 'heading2', 'view': 'h2', 'title': 'Заголовок 2', 'class': 'ck-heading_heading2'},
                {'model': 'heading3', 'view': 'h3', 'title': 'Заголовок 3', 'class': 'ck-heading_heading3'},
                {'model': 'heading4', 'view': 'h4', 'title': 'Заголовок 4', 'class': 'ck-heading_heading4'},
                {'model': 'heading5', 'view': 'h5', 'title': 'Заголовок 5', 'class': 'ck-heading_heading5'},
                {'model': 'heading6', 'view': 'h6', 'title': 'Заголовок 6', 'class': 'ck-heading_heading6'},
            ]
        },
		'balloonToolbar': ['bold', 'italic', '|', 'link', 'insertImage'],
		'heading': {
            'options': [
                {
                    'model': 'paragraph',
                    'title': 'Paragraph',
                    'class': 'ck-heading_paragraph'
                },
                {
                    'model': 'heading1',
                    'view': 'h1',
                    'title': 'Heading 1',
                    'class': 'ck-heading_heading1'
                },
                {
                    'model': 'heading2',
                    'view': 'h2',
                    'title': 'Heading 2',
                    'class': 'ck-heading_heading2'
                },
                {
                    'model': 'heading3',
                    'view': 'h3',
                    'title': 'Heading 3',
                    'class': 'ck-heading_heading3'
                },
                {
                    'model': 'heading4',
                    'view': 'h4',
                    'title': 'Heading 4',
                    'class': 'ck-heading_heading4'
                },
                {
                    'model': 'heading5',
                    'view': 'h5',
                    'title': 'Heading 5',
                    'class': 'ck-heading_heading5'
                },
                {
                    'model': 'heading6',
                    'view': 'h6',
                    'title': 'Heading 6',
                    'class': 'ck-heading_heading6'
                }
            ]
        },
		'image': {
            'toolbar': [
                'toggleImageCaption', 'imageTextAlternative', '|',
                'imageStyle:inline', 'imageStyle:wrapText', 'imageStyle:breakText', '|',
                'resizeImage', '|',
                'ckboxImageEdit'
            ]
	    },
        'table': {
            'contentToolbar': ['tableColumn', 'tableRow', 'mergeTableCells', 'tableProperties', 'tableCellProperties']
        },
		'link': {
            'addTargetToExternalLinks': 'true',
            'defaultProtocol': 'https://',
            'decorators': {
                'toggleDownloadable': {
                    'mode': 'manual',
                    'label': 'Downloadable',
                    'attributes': {
                        'download': 'file'
                    }
                }
            }
	    },
        'placeholder': 'Пишите здесь пост...'
	},
}

TINYMCE_DEFAULT_CONFIG = {
    'plugins': "image,style,list,advimage,styleprops",
    'toolbar': "undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | image | styleprops",
    'advimage_styles': 'float:left; margin: 0 10px 10px 0px; | float:right; margin: 0 0 10px 10px;',
}