# Generated by Django 5.1.7 on 2025-05-17 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videospost',
            name='post',
        ),
        migrations.DeleteModel(
            name='ImagesPost',
        ),
        migrations.DeleteModel(
            name='VideosPost',
        ),
    ]
