# Generated by Django 5.1.7 on 2025-03-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255, null=True, verbose_name='Слаг'),
        ),
    ]
