# Generated by Django 5.1.7 on 2025-05-08 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streets', '0002_defaultconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DefaultConfig',
        ),
    ]
