# Generated by Django 5.1.7 on 2025-05-17 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streets', '0002_remove_videospost_post_delete_imagespost_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Categorie',
        ),
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
