# Generated by Django 5.1.7 on 2025-05-17 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streets', '0003_rename_categories_categorie_rename_posts_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Category',
        ),
    ]
