# Generated by Django 5.1.7 on 2025-03-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streets', '0004_categories_alter_posts_is_published_posts_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='Слаг'),
        ),
    ]
