# Generated by Django 5.1.7 on 2025-04-02 17:22

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streets', '0006_alter_categories_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=255, populate_from='title', unique=True, verbose_name='Слаг'),
        ),
    ]
