# Generated by Django 5.1.7 on 2025-04-11 10:29

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streets', '0010_alter_posts_content_alter_posts_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Контент'),
        ),
    ]
