# Generated by Django 5.1.7 on 2025-04-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streets', '0014_videospost'),
    ]

    operations = [
        migrations.AddField(
            model_name='videospost',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Краткое описание видео(необязательно)'),
        ),
    ]
