# Generated by Django 5.1.7 on 2025-04-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streets', '0017_alter_posts_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.TextField(verbose_name='Контент'),
        ),
    ]
