# Generated by Django 5.1.7 on 2025-04-14 11:35

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streets', '0018_alter_posts_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Контент'),
        ),
    ]
