# Generated by Django 5.1.7 on 2025-04-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streets', '0021_alter_posts_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Видео'),
        ),
    ]
