# Generated by Django 5.1.7 on 2025-05-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streets', '0023_alter_posts_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='date_create',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания поста'),
        ),
        migrations.AddField(
            model_name='posts',
            name='date_update',
            field=models.DateField(auto_now=True, null=True, verbose_name='Дата обновления поста'),
        ),
    ]
