# Generated by Django 5.1.7 on 2025-05-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultconfig',
            name='project_text',
            field=models.TextField(verbose_name='Текст о проекте'),
        ),
    ]
