# Generated by Django 5.1.7 on 2025-05-15 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_alter_participants_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultconfig',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='defaultconfig',
            name='project_text',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='last_name',
        ),
    ]
