# Generated by Django 5.1.7 on 2025-05-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_remove_defaultconfig_project_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultconfig',
            name='project_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название проекта'),
        ),
        migrations.AddField(
            model_name='defaultconfig',
            name='project_preview',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Превью проекта'),
        ),
        migrations.AddField(
            model_name='defaultconfig',
            name='project_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст о проекте'),
        ),
        migrations.AddField(
            model_name='participants',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='participants',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия'),
        ),
    ]
