# Generated by Django 5.1.7 on 2025-05-17 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_defaultconfig_project_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Participants',
            new_name='Participant',
        ),
    ]
