# Generated by Django 5.1.7 on 2025-05-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_rename_participants_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultconfig',
            name='project_name',
            field=models.CharField(default='', max_length=255, verbose_name='Название проекта'),
        ),
        migrations.AlterField(
            model_name='defaultconfig',
            name='project_preview',
            field=models.ImageField(default='', upload_to='photos/', verbose_name='Превью проекта'),
        ),
        migrations.AlterField(
            model_name='defaultconfig',
            name='project_text',
            field=models.TextField(default='', verbose_name='Текст о проекте'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='first_name',
            field=models.CharField(default='', max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='last_name',
            field=models.CharField(default='', max_length=255, verbose_name='Фамилия'),
        ),
    ]
